### ISSUE TITLE
gcr support

### ISSUE THREAD

**Issue by port19x** [sbe-arg/simple-compose-service-updates#2]
**What are you proposing we add or change? Please describe.**
Please add support for the google container registry.

**Additional context**
container image of interest is cadvisor

**Comment by sbe-arg** [comment]
Good point. Ill try to add it!

**Comment by sbe-arg** [comment]
https://github.com/sbe-arg/simple-compose-service-updates/releases/tag/v0.1.1 was too easy, mcr and gcr use the same registry tech.
